version: '3.8'
services:
  mysql-db:
    image: mysql:latest
    env_file:
      - ./src/main/resources/.env
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
